server:
  port: 8082

spring:
  application:
    name: notification-service
  profiles:
    active: dev
  config:
    import: configserver:http://configserver:8071
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/smarthomehub
          jwk-set-uri: http://keycloak:8080/realms/smarthomehub/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/smarthomehub
        registration:
          keycloak:
            client-name: notification-service
            client-id: notification-service
            authorization-grant-type: authorization_code
            client-secret: XEMiM91YjupHHigPvkSZOqIb9R2JsWmM
            scope:
              - openid
              - offline_access
              - profile
              - roles